spring:
  cloud:
    gateway:
      routes:
        - id: gateway-client1 #id是唯一的
          #uri: lb://gateway-client #被代理的服务的uri
          uri: http://localhost:8092
          predicates:
            - Path=/api/client/**
          #            - Weight=service,40
          #- Cookie=test,123456
          #- Method= POST
          #- Header=test,(.*?)
          filters:
            - StripPrefix=2
